FROM debian

# Instalar paquetes necesarios
RUN apt-get update && apt-get install -y \
    nginx \
    openssh-server \
    tor \
    sudo

# Crear usuario ft_onion
RUN useradd -m jusalas- && \
    echo "jusalas-:password" | chpasswd
RUN usermod -aG sudo jusalas-
RUN mkdir /home/jusalas-/.ssh
COPY authorized_keys /home/jusalas-/.ssh 

# Configurar nginx y tor para usar onion service
COPY index.nginx-debian.html /var/www/html/
COPY nginx.conf /etc/nginx/nginx.conf
COPY torrc /etc/tor/torrc
COPY sshd_config /etc/ssh/sshd_config
COPY rickroll-roll.gif /var/www/html/

# Exponer puertos
EXPOSE 80
EXPOSE 4242

# Iniciar servicios
CMD service ssh start && nginx -g 'daemon off;' && tor